# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaminant',
            name='x',
            field=models.CharField(choices=[('a', 'alice'), ('b', 'bob')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
