# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_contaminant_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('land_use', models.CharField(choices=[('unrestricted', 'Unrestricted'), ('commercial', 'Commercial/Industrial')], max_length=24)),
                ('groundwater_use', models.CharField(choices=[('drinking', 'drinking'), ('nondrinking', 'nondrinking')], max_length=24)),
                ('sw_distance', models.CharField(choices=[('close', '< 150'), ('not_close', '>= 150')], max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='contaminant',
            name='x',
        ),
    ]
