# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20170908_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_use', models.CharField(choices=[('unrestricted', 'Unrestricted'), ('commercial', 'Commercial/Industrial')], max_length=24)),
                ('groundwater_use', models.CharField(choices=[('drinking', 'drinking'), ('nondrinking', 'nondrinking')], max_length=24)),
                ('sw_distance', models.CharField(choices=[('close', '< 150'), ('not_close', '>= 150')], max_length=24)),
                ('direct_exposure', models.FloatField()),
                ('soil_vapor_emissions', models.FloatField()),
                ('terrestrial_ecotoxicity', models.FloatField()),
                ('soil_gross_contamination', models.FloatField()),
                ('leaching', models.FloatField()),
                ('dw_toxicity', models.FloatField()),
                ('gw_vapor_emissions', models.FloatField()),
                ('aquatic_ecotoxicity', models.FloatField()),
                ('gw_gross_contamination', models.FloatField()),
                ('shallow_soil_vapor', models.FloatField()),
                ('indoor_air', models.FloatField()),
                ('contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Contaminant')),
            ],
        ),
        migrations.AlterField(
            model_name='sitequery',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
