# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20170909_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContaminant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil', models.FloatField()),
                ('gw', models.FloatField()),
                ('soil_vapor', models.FloatField()),
                ('Contaminant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Contaminant')),
                ('sitequery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.SiteQuery')),
            ],
        ),
    ]
