# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_sitecontaminant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontaminant',
            old_name='Contaminant',
            new_name='contaminant',
        ),
    ]
