# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20170913_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontaminant',
            name='gw',
            field=models.FloatField(verbose_name='Groundwater (μg/L)'),
        ),
        migrations.AlterField(
            model_name='sitecontaminant',
            name='soil',
            field=models.FloatField(verbose_name='Soil (mg/kg)'),
        ),
        migrations.AlterField(
            model_name='sitecontaminant',
            name='soil_vapor',
            field=models.FloatField(verbose_name='Soil Vapor (μg/m³)'),
        ),
    ]
