# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20170914_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlevel',
            name='groundwater_use',
            field=models.CharField(choices=[('drinking', 'Drinking'), ('nondrinking', 'Nondrinking')], max_length=24),
        ),
        migrations.AlterField(
            model_name='actionlevel',
            name='sw_distance',
            field=models.CharField(choices=[('close', '< 150m'), ('not_close', '>= 150m')], max_length=24),
        ),
        migrations.AlterField(
            model_name='sitequery',
            name='groundwater_use',
            field=models.CharField(choices=[('drinking', 'Drinking'), ('nondrinking', 'Nondrinking')], max_length=24),
        ),
        migrations.AlterField(
            model_name='sitequery',
            name='sw_distance',
            field=models.CharField(choices=[('close', '< 150m'), ('not_close', '>= 150m')], max_length=24, verbose_name='Distance from surface water'),
        ),
    ]
